services:
  app:
    image: ghcr.io/pivot-point-ai/aibrigade:latest
    container_name: ivy-league-solutions
    restart: unless-stopped
    ports:
      - "3001:3000"
    env_file:
      - .env.local

